// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Site.Persistence;

namespace Site.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210406170652_Added Identity")]
    partial class AddedIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Site.Domain.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePaths")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b70aa4cc-0376-4df7-826e-29f4c512b996"),
                            Content = "Test content #1",
                            Date = new DateTime(2021, 4, 6, 10, 6, 51, 915, DateTimeKind.Local).AddTicks(8800),
                            ImagePaths = "",
                            Title = "Test title #1"
                        },
                        new
                        {
                            Id = new Guid("24cc5345-09a9-4182-8ba6-91afd2d54345"),
                            Content = "Test content #2",
                            Date = new DateTime(2021, 4, 7, 10, 6, 51, 917, DateTimeKind.Local).AddTicks(3514),
                            ImagePaths = "",
                            Title = "Test title #2"
                        },
                        new
                        {
                            Id = new Guid("a49fd3a8-8d67-4a33-aeeb-8c6300cd2094"),
                            Content = "Test content #3",
                            Date = new DateTime(2021, 4, 8, 10, 6, 51, 917, DateTimeKind.Local).AddTicks(3552),
                            ImagePaths = "",
                            Title = "Test title #3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
