// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Site.Persistence;

namespace Site.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210311225742_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Site.Domain.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePaths")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a4d7344-b8fc-4881-a671-f705b3507ad9"),
                            Content = "Test content #1",
                            Date = new DateTime(2021, 3, 11, 14, 57, 42, 113, DateTimeKind.Local).AddTicks(6664),
                            ImagePaths = "",
                            Title = "Test title #1"
                        },
                        new
                        {
                            Id = new Guid("421c909d-cdb5-4171-96a2-a9f928941fc5"),
                            Content = "Test content #2",
                            Date = new DateTime(2021, 3, 12, 14, 57, 42, 115, DateTimeKind.Local).AddTicks(928),
                            ImagePaths = "",
                            Title = "Test title #2"
                        },
                        new
                        {
                            Id = new Guid("b2538f0d-348a-4a9e-a5c5-8a9b3d6206e2"),
                            Content = "Test content #3",
                            Date = new DateTime(2021, 3, 13, 14, 57, 42, 115, DateTimeKind.Local).AddTicks(961),
                            ImagePaths = "",
                            Title = "Test title #3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
